### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#13]
We need to make icons for the amenities and facilities.

Looks like bostongreenmap is using the icons from here (CC 3.0): https://mapicons.mapsmarker.com/markers/tourism/dogs/. 
- (Non-PARD) AFD Building
- (Non-PARD) Austin Energy Building
- (Non-PARD) Community Center
- (Non-PARD) Cultural Center
- (Non-PARD) Dormitory
- (Non-PARD) EMS Building
- (Non-PARD) Events Center
- (Non-PARD) Fire Station
- (Non-PARD) Health Center
- (Non-PARD) Leased
- (Non-PARD) Library
- (Non-PARD) School
- (Non-PARD)Theatre
- Administrative
- Arbor
- BMX
- Barbecue Pit
- Baseball
- Basketball
- Bathhouse
- Batting Cage
- Bench
- Bike Rack
- Boat Ramp
- Bocce Ball
- Challenge Course
- Climbing Wall
- Concession
- Cricket
- Cultural Center
- Demonstration site
- Drinking Fountain
- Entrance Station
- Environmental Education
- Fitness Station
- Frisbee/Disc Golf
- Garden Center
- Gazebo
- Geneology Center
- Golf 18-hole
- Golf Clubhouse
- Golf Driving Range
- Golf Maintenance facility
- Golf – 9-hole
- Gym
- Historic Building
- Historic Structure
- Horseshoes
- Kiosks
- Living History site
- Maintenance structure
- Managed Habitat
- Marina/Boat storage
- Memorial
- Misc Building
- Mixed Use Field
- Multipurpose
- Mutt Mitt
- Nature Center
- Other
- Parking Lot
- Pavilion
- Performing Arts venue
- Picnic Ground or area
- Picnic Shelter
- Picnic Table
- Pier/Dock
- Plant Nursery
- Playground
- Public Campground
- Pump Station
- RV Dump Station
- Recreation/Community - Large
- Recreation/Community - Small
- Recreation/Community - medium
- Recreation/Community Extra-Large
- Reservable Facility
- Residence
- Restroom
- Retail Store
- Rinse Station
- Scenic Overlook
- Senior Center
- Sign
- Skateboard
- Soccer
- Softball
- Sprayground
- Storage Building
- Swimming Pool
- Teen Center
- Tennis
- Trash Can
- Visual Arts/Crafts
- Volleyball
- Zoo

**Comment by aaronmgdr** [comment]
this looks pretty good
http://map-icons.com/

**Comment by aaronmgdr** [comment]
(Non-PARD) AFD Building
(Non-PARD) Austin Energy Building
(Non-PARD) Community Center
(Non-PARD) Cultural Center
(Non-PARD) Dormitory
(Non-PARD) EMS Building
(Non-PARD) Events Center
(Non-PARD) Fire Station
(Non-PARD) Health Center
(Non-PARD) Leased
(Non-PARD) Library
(Non-PARD) School
(Non-PARD)Theatre
Administrative
Arbor
BMX
Barbecue Pit
Baseball => map-icon-baseball
Basketball 
Bathhouse
Batting Cage
Bench => 
Bike Rack =>  map-icon-bicycle-store
Boat Ramp => map-icon-boat-ramp
Bocce Ball
Challenge Course
Climbing Wall
Concession => map-icon-food
Cricket
Cultural Center 
Demonstration site
Drinking Fountain
Entrance Station
Environmental Education
Fitness Station
Frisbee/Disc Golf
Garden Center
Gazebo
Geneology Center
Golf 18-hole
Golf Clubhouse
Golf Driving Range
Golf Maintenance facility
Golf – 9-hole =>   map-icon-golf
Gym =>   map-icon-gym
Historic Building
Historic Structure
Horseshoes
Kiosks
Living History site
Maintenance structure
Managed Habitat 
Marina/Boat storage => ?
Memorial => ?
Misc Building => ?
Mixed Use Field => ?
Multipurpose => ?
Mutt Mitt => ?
Nature Center => ?
Other => ?
Parking Lot  =>  map-icon-parking
Pavilion => ? 
Performing Arts venue => ?
Picnic Ground or area => map-icon-park 
Picnic Shelter => ?
Picnic Table => map-icon-park
Pier/Dock => map-icon-fishing-pier
Plant Nursery => ?
Playground =>  map-icon-playground
Public Campground => map-icon-campground
Pump Station =>  map-icon-gas-station
RV Dump Station  => map-icon-rv-park
Recreation/Community - Large  => ?
Recreation/Community - Small  => ?
Recreation/Community - medium  => ?
Recreation/Community Extra-Large  => ?
Reservable Facility => ?
Residence => ?
Restroom =>  map-icon-toilet
Retail Store => map-icon-store
Rinse Station => ?
Scenic Overlook =>  map-icon-viewing
Senior Center => ?
Sign => ? 
Skateboard =>   map-icon-skateboarding
Soccer => ?
Softball => map-icon-baseball
Sprayground => ? 
Storage Building => ?
Swimming Pool => map-icon-swimming
Teen Center => ?
Tennis =>  map-icon-tennis
Trash Can =>  ?
Visual Arts/Crafts => ?
Volleyball => ?
zoo => map-icon-zoo

ok so a lot are still missing

**Comment by luqmaan** [comment]
I like the map-icons.com ones since they are SVGs.

Another SVG one: https://www.mapbox.com/maki/

We can stretch Maki to cover most of features. It's missing `bench` and `picnic`, which maybe we can add from somewhere else.
- (Non-PARD) AFD Building => fire-station
- (Non-PARD) Austin Energy Building => building
- (Non-PARD) Community Center => art-gallery, theatre
- (Non-PARD) Cultural Center => art-gallery, theatre
- (Non-PARD) Dormitory => lodging
- (Non-PARD) EMS Building => hospital
- (Non-PARD) Events Center => art-gallery, theatre
- (Non-PARD) Fire Station => fire-station
- (Non-PARD) Health Center => hospital
- (Non-PARD) Leased => building
- (Non-PARD) Library => library
- (Non-PARD) School => school
- (Non-PARD)Theatre => theatre
- Administrative => commercial, building
- Arbor => garden
- BMX => bicycle
- Barbecue Pit => fire-station, fast-food
- Baseball => baseball
- Basketball => basketball
- Bathhouse => swimming
- Batting Cage => baseball
- Bench => ?
- Bike Rack => bicycle
- Boat Ramp => ferry
- Bocce Ball => circle-solid, ?
- Challenge Course => pitch
- Climbing Wall => pitch, ?
- Concession => fast-food
- Cricket => cricket
- Cultural Center => art-gallery, theatre
- Demonstration site => building, ?
- Drinking Fountain => water
- Entrance Station => entrance
- Environmental Education => building, ?
- Fitness Station => pitch
- Frisbee/Disc Golf => pitch, ?
- Garden Center => garden
- Gazebo => building, ?
- Geneology Center => museum
- Golf 18-hole => golf
- Golf Clubhouse => golf
- Golf Driving Range => golf
- Golf Maintenance facility => golf
- Golf – 9-hole => golf
- Gym => pitch
- Historic Building => lighthouse, town-hall, building
- Historic Structure => lighthouse, town-hall, building
- Horseshoes => pitch, ?
- Kiosks => building
- Living History site => building, ?
- Maintenance structure => building
- Managed Habitat => wetland?
- Marina/Boat storage => harbor?
- Memorial => cemetery
- Misc Building => building
- Mixed Use Field => land-use, park2
- Multipurpose => land-use
- Mutt Mitt => dog-park
- Nature Center => garden
- Other => ?
- Parking Lot => parking
- Pavilion => campsite, ?
- Performing Arts venue => theatre
- Picnic Ground or area => park, fast-food, ?
- Picnic Shelter => park, fast-food, ?
- Picnic Table => park, fast-food, ?
- Pier/Dock => harbor
- Plant Nursery => garden
- Playground => playground
- Public Campground => campsite
- Pump Station => fuel, ?
- RV Dump Station => fuel, ?
- Recreation/Community - Large => playground
- Recreation/Community - Small => playground
- Recreation/Community - medium => playground
- Recreation/Community Extra-Large => playground
- Reservable Facility => building, warehouse, telephone, polling-place, ?
- Residence => building, warehouse
- Restroom => toilets
- Retail Store => shop
- Rinse Station => water, ?
- Scenic Overlook => park, park2
- Senior Center => building, ?
- Sign => square-stroked, triangle-stroked
- Skateboard => pitch, ?
- Soccer => soccer
- Softball => baseball
- Sprayground => water, swimming, playground
- Storage Building => warehouse
- Swimming Pool => swimming
- Teen Center => playground, building, ?
- Tennis => tennis
- Trash Can => waste-basket
- Visual Arts/Crafts => art-gallery
- Volleyball => pitch, ?
- Zoo => zoo

**Comment by luqmaan** [comment]
We can use some icons from https://github.com/gravitystorm/openstreetmap-carto (CC0 Public Domain Dedication)
- Picnic Table - https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/picnic.16.svg
- Picnic Shelter - https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shelter2.p.16.png
- Picnic Ground or area - https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/picnic.16.svg
- Bench - https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/bench.16.svg
- Table - https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/picnic.16.svg

**Comment by luqmaan** [comment]
Noun Project (attribution required for free icons, http://blog.thenounproject.com/post/12554806140/the-noun-projects-attribution-requirements)
- Bench - https://thenounproject.com/term/bench/100672/
- Table - https://thenounproject.com/search/?q=picnic-table&i=10581
- Picnic Table - https://thenounproject.com/search/?q=table&i=118680
- Picnic Shelter - https://thenounproject.com/search/?q=picnic-shelter&i=164
- Picnic Area - https://thenounproject.com/search/?q=picnic&i=13130
- BBQ - https://thenounproject.com/search/?q=bbq&i=139656
- Disc Golf - https://thenounproject.com/search/?q=table&i=118680

**Comment by luqmaan** [comment]
Done!
