### ISSUE TITLE
Responsive/mobile friendly/buzzword

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#15]
Try to work well and look good on phones.

Right now the homepage doesn't work well on phones.

The biggest problem is that you can't scroll past the map to see the list of parks.

![ios simulator screen shot jun 18 2015 4 23 56 pm](https://cloud.githubusercontent.com/assets/1275831/8242737/27785ae6-15d7-11e5-825f-b24dfd41ba83.png)

**Comment by johntyree** [comment]
Old and busted
