### ISSUE TITLE
Package as a cordova app

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#16]
We want people to be able to install austingreenmap as an app and be able to view the park data offline.
- [x] Get an iOS app building with Cordova
- [ ] Get an Android app building with Cordova
- [x] iOS icon
- [ ] Android icon
- [x] Splash screen
- [ ] Write script to automate building/packaging
- [x] Publish to App Store
- [ ] Publish to Google Play

**Comment by luqmaan** [comment]
I've gotten it to run on my iPhone! It works much better there too. (I think because the app doesn't freeze waiting for the data load).

https://github.com/open-austin/austingreenmap-cordova

<img src="https://cloud.githubusercontent.com/assets/1275831/8649750/a670c054-2932-11e5-92f7-28b513828c4c.png" width="420" title="blaze it">

**Comment by aaronmgdr** [comment]
sweet

**Comment by luqmaan** [comment]
Submitted to the app store for review.

![image](https://cloud.githubusercontent.com/assets/1275831/8868393/8addc468-319d-11e5-8e49-2bbb89de1c9f.png)
- http://makeappicon.com for the app icon
- http://ticons.fokkezb.nl/ for the splash screen
- https://launchkit.io for the screenshots

**Comment by mateoclarke** [comment]
awesome!

**Comment by aaronmgdr** [comment]
yay

**Comment by luqmaan** [comment]
Yeah! https://itunes.apple.com/us/app/green-map-interactive-map/id1022734155?mt=8

**Comment by scascketta** [comment]
:confetti_ball: 
Congrats you guys!
