### ISSUE TITLE
Router/URLs

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#17]
The app doesn't have a router. The back/forward buttons don't work. You can't share URLs to the parks.

Lets fix this by adding a router.

@johntyree @fremn Would either of you be interested in doing this?

**Comment by aaronmgdr** [comment]
Im up for giving it a go

**Comment by luqmaan** [comment]
Awesome!

**Comment by johntyree** [comment]
:+1: I'm not really sure how it works, actually. In theory, yes, but in practice, no.

**Comment by aaronmgdr** [comment]
any objection to using React-Router?
https://github.com/rackt/react-router

**Comment by luqmaan** [comment]
None, use whatever you feel comfortable with.

**Comment by aaronmgdr** [comment]
hey sorry i dropped the ball in this. I did try to add react-router but got kinda stuck (mostly due to my unfamiliarity with es6) and then swamped with other projects / 4th of July. 

Going to give it another go this week

**Comment by luqmaan** [comment]
Its all good señor.

I started refactoring App.react.jsx into ParkPage.jsx and HomePage.jsx. See the trails branch. Its not quite ready tho.

**Comment by aaronmgdr** [comment]
https://github.com/open-austin/austingreenmap/pull/24

**Comment by aaronmgdr** [comment]
closing this issue
