### ISSUE TITLE
Looking good

### ISSUE THREAD

**Issue by aaronmgdr** [open-austin/austingreenmap#19]
Gotta say this is really starting to be pretty cool. when i pulled that app down today I got  caught up looking at all the parks and amenities near me.

**Comment by luqmaan** [comment]
:fireworks: 

FYI, I usually also deploy the changes to http://open-austin.github.io/austingreenmap/ when I submit a PR. That way you can see what the PR does without running it locally.

To deploy:

```
gulp clean
gulp build
gulp deploy-gh-pages
```
