### ISSUE TITLE
UI change / separate parks list and parkInfo

### ISSUE THREAD

**Issue by aaronmgdr** [open-austin/austingreenmap#25]
When I select a park from the parks list the element that was before in control of showing me the list of parks is now in control of showing me that info park im seeing. Thinking we should break these up for a more intuitive UI. 

maybe the park list could come out of the side? or the could stack? 

Im up for implementing whatever people think is an improvement.

**Comment by johntyree** [comment]
`alert(park.info)`

**Comment by luqmaan** [comment]
Can you draw out the UI you have in mind?
