### ISSUE TITLE
auto indentation/format

### ISSUE THREAD

**Issue by aaronmgdr** [open-austin/austingreenmap#33]
wondering what people think of adding something like http://jscs.info/ to the gulp 

as you may have seen i'm personally pretty bad at following styles manually. on the other hand sometimes automated tools indent in a way you don't like and thats no fun either. (e.g. aligning promises rather than indenting them)

**Comment by luqmaan** [comment]
:+1: Lets add it. The airbnb style guide seems to be the most sane/least controversial. https://github.com/airbnb/javascript

**Comment by aaronmgdr** [comment]
started to do this but kept getting complaints about `import` being used, which is weird since the airbnb styleguide has esnext on.
