### ISSUE TITLE
Add redis and submit to Hack the Block

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#34]
#### DEADLINE

**Submissions** - October 20 at 5:00pm EDT
http://hacktheblock.devpost.com/details/dates

> Build a mobile app that addresses community issues using ObjectRocket by Rackspace's Data Services and you’ll not only have a shot at some cash prizes, but you’ll also be helping create some change in your own neighborhood.

http://hacktheblock.challengepost.com/

Lets add redis! Some ways we can use redis
- Store user comments
- Store user ratings on parks
- Leaderboard for parks

Any others?

**Comment by prestonp** [comment]
I think redis can make leaderboard-esque features trivial. Perhaps we could implement a list of the most popular parks by past day, week, or year

http://highscalability.com/blog/2011/7/6/11-common-web-use-cases-solved-in-redis.html

**Comment by aaronmgdr** [comment]
https://matt.sh/redis-geo

**Comment by luqmaan** [comment]
Too late.
