### ISSUE TITLE
Cluster markers

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#35]
I think we can do this by extending a react-leaflet component to call addMarker/removeMarker from https://github.com/Leaflet/Leaflet.markercluster.

Related to #26

**Comment by luqmaan** [comment]
Ooooh https://github.com/paulserraino/react-geojson-cluster

@paulserraino wanna add this to ParkMap?

**Comment by paulserraino** [comment]
yep! I already started. I'll send a PR later today.

**Comment by luqmaan** [comment]
:fire:

**Comment by luqmaan** [comment]
Fixed by @paulserraino's awesome PR.
