### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by aaronmgdr** [open-austin/austingreenmap#36]

**Comment by luqmaan** [comment]
Oops, adding GPL

**Comment by luqmaan** [comment]
Actually, I'd like to to release Austin Green Map into the public domain. This way no person owns the copyright to it.

@fremn @prestonp @johntyree How do you feel about this? Do you agree to making your existing/future contributions part of the public domain? `I dedicate any and all copyright interest in this software to the public domain`.

http://unlicense.org

> ### Unlicensing Contributions
> 
> In order to ensure your project remains completely free and unencumbered by anyone's copyright monopoly, it is advisable that you ask any major contributors to explicitly dedicate their code-base contributions to the public domain.
> 
> This removes any possible ambiguity as to what terms somebody might have thought they were contributing under, in case of a future dispute. These concerns are not unique to public domain software. Most large, established open-source projects have a Contributor License Agreement (CLA) process, of varying degrees of formality.
> 
> At minimum, you might ask your contributors to accompany any non-trivial patches with a simple statement like the following:
> 
> > I dedicate any and all copyright interest in this software to the
> > public domain. I make this dedication for the benefit of the public at
> > large and to the detriment of my heirs and successors. I intend this
> > dedication to be an overt act of relinquishment in perpetuity of all
> > present and future rights to this software under copyright law.
> 
> Better yet is to ask the major contributors to digitally sign a more explicit copyright release (see an example WAIVER file), and then to keep a record of such signatures in an AUTHORS file accompanying your software. Using GnuPG, contributors can sign a copyright waiver file as follows:
> 
> `$ gpg --no-version --armor --sign WAIVER`
> 
> Note that if a contributor makes significant changes or enhancements in his capacity as an employee of some formal organization, then the above may be insufficient and you would additionally need to ask for a copyright disclaimer signed by a company officer. For more information, have a look at how the SQLite project handles this. The Free Software Foundation (FSF) also provides an example of a simple copyright disclaimer to be signed by an employer.

**Comment by aaronmgdr** [comment]
im good with that.
`I dedicate any and all copyright interest in this software to the public domain`

**Comment by prestonp** [comment]
:+1:

**Comment by johntyree** [comment]
Is there a reason to release to public domain over any of the various licenses designed for this kind of work? [CC-BY](https://creativecommons.org/licenses/by/2.0/) for example? Then at least your name can go along with all your hard work.

**Comment by luqmaan** [comment]
Yes there is a reason. Those licenses don't answer the question of who owns the copyright.

 I don't think Open Austin is a legal entity that can hold the copyright. "Contributors" is a very ambiguous term. See the discussion at https://github.com/open-austin/austingreenmap/pull/37.

If you want to use a Creative Commons license, the equivalent would be CC0. http://creativecommons.org/publicdomain/zero/1.0/.

More licenses http://choosealicense.com/

**Comment by luqmaan** [comment]
Also, we'd like to use a license that can work for all the Open Austin projects. Not just Austin Green Map.

**Comment by luqmaan** [comment]
Actually, I propose we use this license. http://nonwhiteheterosexualmalelicense.org

**Comment by johntyree** [comment]
Have we looked at what CodeForAmerica says about this? I overheard at the last meetup that Open Austin falls under their umbrella.

**Comment by luqmaan** [comment]
I asked on the Code for America #brigade Slack channel and got responses about a few open source licenses, but no answers about copyright ownership.

Again, the problem with these licenses is that they don't answer the question of copyright ownership.

Who should own the copyright for this repo? Should it be me? Should it be "the contributors?" Is the language "contributors" clear? I don't think so.

I think the most simple solution is to dedicate our work to the public domain.

The concern for our work being used without due credit is valid.

But, what is the likelihood of that happening? In the event our work is used without due credit, will we really have the resources to enforce the license we choose is respected?

If the work we do on a civic project is good enough for others to _steal_, then we've done our job.

What other concerns do you have about dedicating our work on Open Austin civic projects to the public domain?

**Comment by luqmaan** [comment]
The cfa_template repo assigns the copyright to Code For America https://github.com/codeforamerica/cfa_template/blob/master/LICENSE.mkd

**Comment by johntyree** [comment]
I think "the contributors" is ambiguous in the absence of a commit log. But we have one so I don't see how that applies.

As we talked about offline, I'm fine with public domain or CC0 or whatever it is that is settled on. I just wanted to make sure that it was an intentional choice since it _does_ leave the code open for use in all kinds of nefarious ways. I think the iTunes EULA used to have language about not using their product for creating nuclear weapons :grinning:.

**Comment by aaronmgdr** [comment]
so we append `no nukes mkay` to unlicence ? 

how about each line is "copyright those who have committed changes to it"  see commit log for specific licenses for each commit.  :dizzy_face: 

in all seriousness public domain :+1:

**Comment by luqmaan** [comment]
People can contribute without committing.

Two examples:
- your work on Saturday figuring out the PARD data
- a designer who doesn't want to use github

**Comment by luqmaan** [comment]
Also just as a reminder the Unlicense has a warranty clause.

**Comment by johntyree** [comment]
- Copyright has nothing to do with research, which can't be "copied" anyway. It covers the tangible work.
- Commits can specify authors separately from committer for exactly this reason.
- Public domain is fine.

**Comment by johntyree** [comment]
For clarity: I am totally fine with my contributions to this work being in the public domain.

**Comment by luqmaan** [comment]
:deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :evergreen_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :evergreen_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree: :deciduous_tree:

**Comment by johntyree** [comment]
:fallen_leaf:

**Comment by luqmaan** [comment]
Can you spot the difference?

**Comment by aaronmgdr** [comment]
:tanabata_tree:
