### ISSUE TITLE
Basic README

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/austingreenmap#4]
I wanted to check out the UI branch but I haven't done anything in React.

Their getting started page suggests all you need is:

`npm install -g react-tools` && `jsx --watch src/ build/`

...but I didn't know what source or build to watch :disappointed:.

What npm dependencies are there? How to I install them and serve this up to a localhost? 

@luqmaan @johntyree

**Comment by luqmaan** [comment]
Will add readme soon. Not much to see for now.

Npm install -g gulp
Npm install
Gulp clean && gulp

**Comment by aaronmgdr** [comment]
it looks like babel https://babeljs.io/

**Comment by mateoclarke** [comment]
also had to run
`npm install gulp-symlink --save-dev`

**Comment by johntyree** [comment]
:+1:
