### ISSUE TITLE
The dropdown is painful

### ISSUE THREAD

**Issue by luqmaan** [open-austin/austingreenmap#42]
The dropdown is painful, especially on mobile.

Since it is also the main interaction point of the app, we should think about how to make it better.

**Comment by aaronmgdr** [comment]
no ideas yet but it seems we have a few areas where the ui needs some help (this, the one about people not knowing what the app is for,my one about the park list disappearing when in park view).

maybe the solutions to these are related (ui wise) maybe not. thats what im thinking about. 

@luqmaan you are referring to the dropdown where ammenity types are selected yes?

**Comment by luqmaan** [comment]
@prestonp and i did some wireframing last night and i think we have a pretty good solution. i'll be implementing it over the next week.

**Comment by aaronmgdr** [comment]
cool
